name: AccuKnox Secret Scan Workflow

on:
  push:
    branches:
      - secret

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AccuKnox Secret Scan TEST
        uses: accuknox/secret-scan-action@latest
        with:
          with:
          branch: "main"                             # Optional
          results: " "                               # Optional
          exclude_paths: "tests/,docs/"              # Optional
          additional_arguments: ""                   # Optional
          base_command: ""                           # Optional
          output_format: json                        # Optional
          output_file_path: "./secret_results.json"  # Optional
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true                            # Optional
