name: AccuKnox Secret Scan Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AccuKnox Secret Scan TEST
        uses: accuknox/secret-scan-action@latest

        with:
          branch: "main"
          results: ""
          exclude_paths: ""
          additional_arguments: ""
          base_command: ""
          output_format: "json"
          output_file_path: "./secret_results.json"

          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}

          soft_fail: true
